# Generated by Django 5.2.15 on 2026-07-05 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='usuario',
            new_name='user',
        ),
    ]
