# Generated by Django 5.2.15 on 2026-07-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_rename_usuario_cliente_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email_bienvenida_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
