name: Django CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Esto es clave: definimos los servicios que necesitamos
    services:
      db:
        image: postgres:15
        env:
          POSTGRES_DB: tu_base_de_datos
          POSTGRES_USER: user
          POSTGRES_PASSWORD: Mami_pro42
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Stop GitHub's default Postgres
        run: sudo systemctl stop postgresql
      
      - name:
        run: |
          docker compose upd -d
          sleep 30
          docker compose exec -T web python manage.py migrate
          docker compose exec -T web python manage.py test